os:
  - linux
  - osx

language: c

env:
  matrix:
    - CONDA_PY=2.7
    - CONDA_PY=3.6
    - CONDA_PY=3.7
  global:
    - PYSAM_LINKING_TEST=1
    - TWINE_USERNAME=
    - secure: ''

_deploy_common: &deploy_common
  if: tag IS present
  install:
    - python3 -m pip install cibuildwheel twine

matrix:
  include:
    - stage: deploy
      os: linux
      language: python
      python: '3.5'
      services:
        - docker
      env:
        - CIBW_BEFORE_BUILD="yum install -y zlib-devel bzip2-devel xz-devel && pip install -r requirements.txt"
        - CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"'
      <<: *deploy_common
      script:
        - set -e
        - cibuildwheel --output-dir dist
        - python3 -m pip install Cython
        - python3 setup.py sdist
        - twine check dist/*
        - ls -lh dist/
        - twine upload --skip-existing dist/*
    - stage: deploy
      os: osx
      language: generic
      env:
        - CIBW_BEFORE_BUILD="pip install -r requirements.txt"
        - CIBW_ENVIRONMENT='HTSLIB_CONFIGURE_OPTIONS="--disable-libcurl"'
      addons: {}
      <<: *deploy_common
      script:
        - set -e
        - cibuildwheel --output-dir dist
        - twine check dist/*
        - ls -lh dist/
        - twine upload --skip-existing dist/*

addons:
  apt:
    packages:
    - gcc
    - g++

script:
  # - ./devtools/run_tests_travis.sh
  - echo "Tests skipped!"

notifications:
  email:
    - andreas.heger@gmail.com
